# Generated by Django 4.2.7 on 2026-02-13 18:31

import architecture_ar.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.FileField(help_text='Blueprint/plan file for AR tracking (JPG, PNG, WebP, PDF).', upload_to=architecture_ar.models.blueprint_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blueprint',
                'verbose_name_plural': 'Blueprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='3D model file (FBX, OBJ, GLB, GLTF).', upload_to=architecture_ar.models.model3d_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['fbx', 'obj', 'glb', 'gltf'])])),
                ('scale', models.FloatField(default=1.0, help_text='Scale factor for the 3D model in AR scene.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model3d', to='architecture_ar.blueprint')),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Models',
                'ordering': ['-created_at'],
            },
        ),
    ]
