# Generated by Django 4.2.7 on 2026-02-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_ar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, this content will be visible to ALL users.'),
        ),
    ]
