# Generated by Django 4.2.7 on 2026-02-25 14:47

import architecture_ar.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_ar', '0002_blueprint_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='original_format',
            field=models.CharField(blank=True, help_text='Formato original (PDF, PNG, etc)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model3d',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='image',
            field=models.FileField(help_text='Blueprint file (JPG, PNG, WebP, PDF). Se convertirá automáticamente a WebP.', upload_to=architecture_ar.models.blueprint_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
