# Generated by Django 4.2.7 on 2026-03-04 20:40

import architecture_ar.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_ar', '0004_model3d_original_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='image',
            field=models.FileField(help_text='Blueprint file (JPG, PNG, WebP, PDF). Se convertirá automáticamente a JPG optimizado.', upload_to=architecture_ar.models.blueprint_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(help_text='3D model file. Upload FBX or OBJ and we convert it automatically to GLB. Accepted formats: FBX, GLB, GLTF, OBJ.', upload_to=architecture_ar.models.model3d_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.fbx', '.glb', '.gltf', '.obj'])]),
        ),
    ]
