# Generated by Django 4.2.7 on 2026-03-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_ar', '0005_alter_blueprint_image_alter_model3d_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='image_size',
            field=models.FloatField(default=0.0, help_text='Tamaño de la imagen preview en MB'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='model_size',
            field=models.FloatField(default=0.0, help_text='Tamaño del archivo 3D/PDF en MB'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='resolution',
            field=models.CharField(blank=True, help_text='Resolución de la vista previa (ej: 1920x1080)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True=Proyecto público, False=Privado'),
        ),
    ]
