# Generated by Django 4.2.7 on 2026-02-13 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(help_text='Target image for AR tracking (JPG, PNG, WebP).', upload_to=image_tracking.models.tracking_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracking Image',
                'verbose_name_plural': 'Tracking Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(help_text='Video file to display in AR (MP4, WebM, MOV, AVI).', upload_to=image_tracking.models.tracking_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='image_tracking.trackingimage')),
            ],
            options={
                'verbose_name': 'Tracking Video',
                'verbose_name_plural': 'Tracking Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
