# Generated by Django 4.2.7 on 2026-02-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingimage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, this content will be visible to ALL users (e.g. for ads or public art).'),
        ),
    ]
