# Generated by Django 4.2.7 on 2026-02-24 21:40

import django.core.validators
from django.db import migrations, models
import image_tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tracking', '0002_trackingimage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingimage',
            name='aspect_ratio',
            field=models.CharField(choices=[('16:9', 'Horizontal (16:9)'), ('9:16', 'Vertical (9:16)')], default='16:9', max_length=10),
        ),
        migrations.AlterField(
            model_name='trackingimage',
            name='image',
            field=models.ImageField(help_text='Target image for AR tracking.', upload_to=image_tracking.models.tracking_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), image_tracking.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='trackingimage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trackingvideo',
            name='video',
            field=models.FileField(help_text='Video file to display in AR.', upload_to=image_tracking.models.tracking_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi']), image_tracking.models.validate_video_size]),
        ),
    ]
