# Generated by Django 4.2.7 on 2026-02-25 14:47

import django.core.validators
from django.db import migrations, models
import image_tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tracking', '0003_trackingimage_aspect_ratio_alter_trackingimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en bytes de la imagen optimizada', null=True),
        ),
        migrations.AddField(
            model_name='trackingimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingvideo',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en bytes', null=True),
        ),
        migrations.AlterField(
            model_name='trackingimage',
            name='image',
            field=models.ImageField(help_text='Target image for AR tracking. Se convertirá automáticamente a WebP.', upload_to=image_tracking.models.tracking_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), image_tracking.models.validate_image_size]),
        ),
    ]
