# Generated by Django 4.2.7 on 2026-03-04 20:40

import django.core.validators
from django.db import migrations, models
import image_tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tracking', '0004_trackingimage_file_size_trackingimage_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingimage',
            name='image',
            field=models.ImageField(help_text='Target image for AR tracking. Se convertirá automáticamente a JPG optimizado.', upload_to=image_tracking.models.tracking_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), image_tracking.models.validate_image_size]),
        ),
    ]
