# Generated by Django 4.2.7 on 2026-03-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tracking', '0005_alter_trackingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingimage',
            name='image_size',
            field=models.FloatField(default=0.0, help_text='Tamaño de la imagen en MB'),
        ),
        migrations.AddField(
            model_name='trackingimage',
            name='physical_width',
            field=models.FloatField(default=0.1, help_text='Ancho físico de la imagen en metros (para AR)'),
        ),
        migrations.AddField(
            model_name='trackingimage',
            name='resolution',
            field=models.CharField(blank=True, help_text='Resolución de la imagen (ej: 1920x1080)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trackingimage',
            name='video_size',
            field=models.FloatField(default=0.0, help_text='Tamaño del video en MB'),
        ),
        migrations.AlterField(
            model_name='trackingimage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True=Proyecto público, False=Privado'),
        ),
    ]
