# Generated by Django 4.2.7 on 2026-09-28 14:35

from django.db import migrations, models
import image_tracking.models
import random


def populate_activation_pins(apps, schema_editor):
    """Asigna PIN único a registros existentes que no lo tengan."""
    TrackingImage = apps.get_model('image_tracking', 'TrackingImage')
    chars = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"
    for item in TrackingImage.objects.filter(activation_pin__isnull=True):
        pin = ''.join(random.choices(chars, k=6))
        while TrackingImage.objects.filter(activation_pin=pin).exists():
            pin = ''.join(random.choices(chars, k=6))
        item.activation_pin = pin
        item.save(update_fields=['activation_pin'])


class Migration(migrations.Migration):

    dependencies = [
        ('image_tracking', '0006_trackingimage_image_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingimage',
            name='activation_pin',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='PIN único para desbloquear la experiencia desde la app móvil',
                max_length=20,
                null=True,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='trackingimage',
            name='qr_code_image',
            field=models.ImageField(
                blank=True,
                help_text='Imagen del código QR generado para activación en la app',
                null=True,
                upload_to=image_tracking.models.tracking_qr_code_upload_path
            ),
        ),
        migrations.RunPython(populate_activation_pins, reverse_code=migrations.RunPython.noop),
    ]
