"""
Django settings for loveart project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-%cphr=1tcxii@eyiaqi0u5j@b1ww)4c+#-9k3ifwh8dopil-uv')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# CSRF Trusted Origins for Railway
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'storages',
    'django_cleanup.apps.CleanupConfig',
    # Apps del proyecto
    'image_tracking',
    'architecture_ar',
    'users',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# CORS CONFIGURATION
# ============================================
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')

# ============================================
# REST FRAMEWORK CONFIGURATION
# ============================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ============================================
# SIMPLE JWT CONFIGURATION
# ============================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,       # Emite nuevo refresh en cada uso
    'BLACKLIST_AFTER_ROTATION': True,    # Invalida el refresh anterior
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),    # Frontend debe enviar: Authorization: Bearer <token>
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ============================================
# DRF-SPECTACULAR (API Docs)
# ============================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'LoveArt AR API',
    'DESCRIPTION': 'API for managing AR tracking images and videos for Unity consumption.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

ROOT_URLCONF = 'loveart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loveart.wsgi.application'


# ============================================
# DATABASE CONFIGURATION
# ============================================
# Prioridad:
# 1. Si existe DATABASE_URL (Railway/Render) -> usa dj_database_url
# 2. Si no -> usa variables individuales (Docker Compose local)

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parsing de la URL de forma robusta
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
    
    # Si es el pooler (6543), CONN_MAX_AGE debe ser 0. Si es directo (5432), usamos 600.
    DATABASES['default']['CONN_MAX_AGE'] = 0 if ':6543' in DATABASE_URL else 600
    
    # Forzar SSL para Supabase (indispensable)
    if 'supabase' in DATABASE_URL:
        DATABASES['default'].setdefault('OPTIONS', {})
        DATABASES['default']['OPTIONS']['sslmode'] = 'require'
    
    print(f"✅ Base de datos: Usando {'Pooler' if ':6543' in DATABASE_URL else 'Directa'} (Supabase)")
else:
    # Desarrollo local: Docker Compose
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "my_database"),
            "USER": os.environ.get("POSTGRES_USER", "admin"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "admin"),
            "HOST": os.environ.get("DATABASE_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
    print(f"✅ Base de datos: Usando configuración local (Host: {DATABASES['default']['HOST']})")



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# FILE UPLOAD LIMITS (for video uploads)
# ============================================
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600    # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600    # 100 MB

# ============================================
# EMAIL — Gmail API via OAuth2 (same as n8n Gmail node)
# ============================================
# One-time setup: docker exec -it django python manage.py setup_gmail_oauth
# Then add GMAIL_REFRESH_TOKEN to .env and restart Docker.

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',  # Fallback: print to console
)

# Gmail OAuth2 credentials (reuse existing Google OAuth app)
GMAIL_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GMAIL_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
GMAIL_REFRESH_TOKEN = os.environ.get('GMAIL_REFRESH_TOKEN', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'LoveArt <noreply@loveart.app>')

# ============================================
# AWS S3 & CLOUDFRONT CONFIGURATION
# ============================================
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')

# Dominio de CloudFront (ejemplo: d111111abcdef8.cloudfront.net)
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN')

if all([AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME]):
    STORAGES = {
        "default": {
            "BACKEND": "loveart.storages_backends.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "loveart.storages_backends.StaticStorage",
        },
    }
    
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    
    # SigV4 is required for some regions
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # Desactivar ACLs (necesario para buckets nuevos de AWS que no permiten ACLs)
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    
    # URL configurations
    if AWS_S3_CUSTOM_DOMAIN:
        # Si hay CloudFront, usamos ese dominio
        STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/uploads/'
    else:
        # Si no, usamos el dominio de S3 directamente
        STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/'
        MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/uploads/'

    print(f"✅ Storage: Usando AWS S3 (Bucket: {AWS_STORAGE_BUCKET_NAME})")
    if AWS_S3_CUSTOM_DOMAIN:
        print(f"✅ CloudFront: Habilitado (Dominio: {AWS_S3_CUSTOM_DOMAIN})")
else:
    print("ℹ️ Storage: Usando almacenamiento local (Faltan variables AWS en .env)")


