# Generated by Django 4.2.7 on 2026-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Habilitar manualmente si el usuario pagó vía WhatsApp'),
        ),
    ]
