# Generated by Django 4.2.7 on 2026-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Marcar para dar acceso de administrador en el portal frontend'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Se activa automáticamente al verificar el OTP'),
        ),
    ]
