# Generated by Django 4.2.7 on 2026-09-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_verified_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última verificación por código OTP', null=True),
        ),
    ]
