# Generated by Django 4.2.7 on 2026-03-09 21:23

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='loveARt', max_length=255)),
                ('version', models.CharField(help_text='Ej: 1.0.0, v2.1', max_length=50)),
                ('apk_file', models.FileField(help_text='Subir el archivo .apk generado en Unity.', upload_to=core.models.app_build_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])])),
                ('description', models.TextField(blank=True, default='')),
                ('is_latest', models.BooleanField(default=True, help_text='Si es la versión actual para descargar desde la landing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Build',
                'verbose_name_plural': 'App Builds',
                'ordering': ['-created_at'],
            },
        ),
    ]
